name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hydex:
    path: ../

  assets:
    path: ../assets

  widgetbook_annotation: ^3.5.0
  widgetbook: ^3.14.3
  flutter_riverpod: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true

